name: deploying Hexo project to GitHub pages

on:
  push:
    branches:
      - master # master branch triggers this action when there is a push behavior

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clear NPM cache
        run: npm cache clean --force

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npx hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
